const CATALOG = [
  {
    id: "midnight-run",
    title: "Midnight Run",
    type: "movie",
    row: "Trending Now",
    isNew: true,
    year: 2025,
    duration: "1h 42m",
    rating: "PG-13",
    description: "A late-night thriller placeholder title built to make your catalog feel cinematic and real.",
    hero: false,
    youtubeId: "jNQXAC9IVRw",
    image: "https://images.unsplash.com/photo-1517604931442-7e0c8ed2963c?auto=format&fit=crop&w=1200&q=80",
    preview: "https://interactive-examples.mdn.mozilla.net/media/cc0-videos/flower.mp4"
  },
  {
    id: "dark-city",
    title: "Dark City",
    type: "movie",
    row: "Trending Now",
    isNew: false,
    year: 2024,
    duration: "1h 55m",
    rating: "R",
    description: "A dark city crime story placeholder page with a moody tone and sharp visuals.",
    hero: true,
    youtubeId: "dQw4w9WgXcQ",
    image: "https://images.unsplash.com/photo-1485846234645-a62644f84728?auto=format&fit=crop&w=1200&q=80",
    preview: "https://interactive-examples.mdn.mozilla.net/media/cc0-videos/flower.mp4"
  },
  {
    id: "neon-heat",
    title: "Neon Heat",
    type: "movie",
    row: "Trending Now",
    isNew: true,
    year: 2026,
    duration: "1h 38m",
    rating: "PG-13",
    description: "A nightlife drama placeholder title with bright colors and a slick streaming vibe.",
    hero: false,
    youtubeId: "ysz5S6PUM-U",
    image: "https://images.unsplash.com/photo-1478720568477-152d9b164e26?auto=format&fit=crop&w=1200&q=80",
    preview: "https://interactive-examples.mdn.mozilla.net/media/cc0-videos/flower.mp4"
  },
  {
    id: "late-shift",
    title: "Late Shift",
    type: "series",
    row: "Trending Now",
    isNew: false,
    year: 2025,
    duration: "8 Episodes",
    rating: "TV-14",
    description: "A moody mystery series placeholder that gives your site a long-form TV feel.",
    hero: false,
    youtubeId: "jNQXAC9IVRw",
    image: "https://images.unsplash.com/photo-1440404653325-ab127d49abc1?auto=format&fit=crop&w=1200&q=80",
    preview: "https://interactive-examples.mdn.mozilla.net/media/cc0-videos/flower.mp4"
  },
  {
    id: "cold-signal",
    title: "Cold Signal",
    type: "series",
    row: "Popular Shows",
    isNew: false,
    year: 2025,
    duration: "10 Episodes",
    rating: "TV-MA",
    description: "A cold-case style show placeholder with a gritty detective vibe.",
    hero: false,
    youtubeId: "jNQXAC9IVRw",
    image: "https://images.unsplash.com/photo-1500530855697-b586d89ba3ee?auto=format&fit=crop&w=1200&q=80",
    preview: "https://interactive-examples.mdn.mozilla.net/media/cc0-videos/flower.mp4"
  },
  {
    id: "red-harbor",
    title: "Red Harbor",
    type: "series",
    row: "Popular Shows",
    isNew: true,
    year: 2026,
    duration: "6 Episodes",
    rating: "TV-14",
    description: "A harbor-town crime series placeholder that feels built for binge watching.",
    hero: false,
    youtubeId: "jNQXAC9IVRw",
    image: "https://images.unsplash.com/photo-1497032628192-86f99bcd76bc?auto=format&fit=crop&w=1200&q=80",
    preview: "https://interactive-examples.mdn.mozilla.net/media/cc0-videos/flower.mp4"
  },
  {
    id: "static-nights",
    title: "Static Nights",
    type: "series",
    row: "Popular Shows",
    isNew: false,
    year: 2024,
    duration: "12 Episodes",
    rating: "TV-14",
    description: "A late-night broadcast style placeholder series for a darker catalog section.",
    hero: false,
    youtubeId: "jNQXAC9IVRw",
    image: "https://images.unsplash.com/photo-1518998053901-5348d3961a04?auto=format&fit=crop&w=1200&q=80",
    preview: "https://interactive-examples.mdn.mozilla.net/media/cc0-videos/flower.mp4"
  },
  {
    id: "afterlight",
    title: "Afterlight",
    type: "movie",
    row: "Popular Shows",
    isNew: true,
    year: 2026,
    duration: "2h 03m",
    rating: "PG-13",
    description: "A clean sci-fi placeholder feature film for your catalog.",
    hero: false,
    youtubeId: "jNQXAC9IVRw",
    image: "https://images.unsplash.com/photo-1513106580091-1d82408b8cd6?auto=format&fit=crop&w=1200&q=80",
    preview: "https://interactive-examples.mdn.mozilla.net/media/cc0-videos/flower.mp4"
  },
  {
    id: "blackout",
    title: "Blackout",
    type: "movie",
    row: "Action & Crime",
    isNew: false,
    year: 2025,
    duration: "1h 47m",
    rating: "R",
    description: "A gritty action placeholder title with a darker, fast-moving tone.",
    hero: false,
    youtubeId: "jNQXAC9IVRw",
    image: "https://images.unsplash.com/photo-1508057198894-247b23fe5ade?auto=format&fit=crop&w=1200&q=80",
    preview: "https://interactive-examples.mdn.mozilla.net/media/cc0-videos/flower.mp4"
  },
  {
    id: "no-witness",
    title: "No Witness",
    type: "movie",
    row: "Action & Crime",
    isNew: false,
    year: 2024,
    duration: "1h 36m",
    rating: "R",
    description: "A crime drama placeholder page designed to make your action section feel legit.",
    hero: false,
    youtubeId: "jNQXAC9IVRw",
    image: "https://images.unsplash.com/photo-1516035069371-29a1b244cc32?auto=format&fit=crop&w=1200&q=80",
    preview: "https://interactive-examples.mdn.mozilla.net/media/cc0-videos/flower.mp4"
  },
  {
    id: "street-theory",
    title: "Street Theory",
    type: "series",
    row: "Action & Crime",
    isNew: true,
    year: 2026,
    duration: "7 Episodes",
    rating: "TV-MA",
    description: "A street-level thriller placeholder with room to become a real long-form show later.",
    hero: false,
    youtubeId: "jNQXAC9IVRw",
    image: "https://images.unsplash.com/photo-1492691527719-9d1e07e534b4?auto=format&fit=crop&w=1200&q=80",
    preview: "https://interactive-examples.mdn.mozilla.net/media/cc0-videos/flower.mp4"
  },
  {
    id: "lockstep",
    title: "Lockstep",
    type: "series",
    row: "Action & Crime",
    isNew: false,
    year: 2025,
    duration: "9 Episodes",
    rating: "TV-14",
    description: "A high-pressure crime placeholder series for your heavier section.",
    hero: false,
    youtubeId: "jNQXAC9IVRw",
    image: "https://images.unsplash.com/photo-1499364615650-ec38552f4f34?auto=format&fit=crop&w=1200&q=80",
    preview: "https://interactive-examples.mdn.mozilla.net/media/cc0-videos/flower.mp4"
  }
];
